# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestCase
 pod 'SwiftFormat/CLI'

  target 'UnitTestCaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTestCaseUITests' do
    # Pods for testing
  end

end
